### ISSUE TITLE
Debug artikel images

### ISSUE THREAD

**Issue by Shannafdnd** [fdnd-agency/red-pers#30]

**Comment by RubenErhardt** [comment]
Goed bezig !!

![nice](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXM4aXltZWljc2l1NzJ2N2Q2MjJtNzYxOTI5M2xqZ2ZoeGl4YXB5dyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qPcX2mzk3NmjC/giphy.gif)
